### ISSUE TITLE
configuring passThrough and contentTypes

### ISSUE THREAD

**Issue by petesiss** [tes/compoxure#102]
A backend config already has ``["application/javascript", "html"]`` in the ``contentTypes`` config, in conjunction with``"passThrough": true``.

How would you now configure compoxure to pass through your sitemap.xml from that backend, with the correct content-type header, assuming:
- the backend provides the full document
- it shouldn't be parsed
- the backend has set the correct application/xml content-type header on the response

Not sure if there's a bug, if it's just not something that's catered for, or if I'm misunderstanding the purpose of that content types config, but adding ``application/xml`` to my contentTypes array seems to have no impact on what is returned or parsed, or on the resulting content-type headers. The xml document always comes back with content-type text/html.

**Comment by gabceb** [comment]
@petesiss can you confirm your request passes all the conditions at https://github.com/tes/compoxure/blob/c32966e2912a6303967d0720ad31aba79d0817dd/src/middleware/passthrough.js#L8-L16 to be considered a passthough request?

**Comment by petesiss** [comment]
@gabceb no, in my testing it matches the condition ``req.contentType === 'html'``

**Comment by petesiss** [comment]
@gabceb Ive spent a little more time on this and it seems to me that there is no way to configure Compoxure to respect application/xml as well as application/javascript that it is already configured for.

Would be great to get your perspective on this, especially if I've missed something.

Right now xml sitemaps have the correct content type when sent from the backend, but Compoxure returns them to the client as text/html.

**Comment by cliftonc** [comment]
If we address #41 it will solve this, moving the fix over there.
