### ISSUE TITLE
Error in running example

### ISSUE THREAD

**Issue by mandale28** [tes/compoxure#105]
Tried to run start after downloading.
I am getting the cookie parser error while downloading & running by zip ( and using cloning -> we are getting other error 'cacheFactory error')

![image](https://user-images.githubusercontent.com/33297883/32344149-14f4725e-bfc3-11e7-94b4-6344315cb209.png)
Appreciate your help..

**Comment by nutan06** [comment]
I am also facing similar issue.
After installing cookie-parser got the error of no cache engine.
How to rectify this?
Thanks in advance.

**Comment by cliftonc** [comment]
I'll take a look this morning.  Looks like the dependencies arent right - what version of node / npm?

**Comment by mandale28** [comment]
info using npm@5.5.1
info using node@v8.9.0

**Comment by r-ghilardi** [comment]
@nutan06 to solve cache issue you have to use a cache engine or set `engine: "nocache"` in `example/config.json`configuration files:
```
  "cache": {
    "defaultNoCacheHeaders": {
      "cache-control": "private, no-cache, max-age=0, must-revalidate, no-store"
    },
    "engine": "nocache",
    "apiEnabled": true
  }
```

**Comment by nutan06** [comment]
@r-ghilardi Thanks for the suggestion will try it.

**Comment by nutan06** [comment]
Thanks for the update Clifton
