### ISSUE TITLE
Add debug header

### ISSUE THREAD

**Issue by cliftonc** [tes/compoxure#106]
We should add a header / output that shows debug info when asked in a url, e.g. no one understood why PC was over-writing the cache-control header.

It was doing it because there was a fragment in page that wasn't cached, and so triggered this safety catch:

https://github.com/tes/compoxure/blob/36a0e9665465a009ff6e32d822d09688ee13fb45/src/middleware/htmlparser.js#L130

**Comment by ksnll** [comment]
We can output some more informations while using cx-debug

**Comment by sithmel** [comment]
Added a facility to log these kind of info in the browser console. You need to use cx-debug to see that.
