### ISSUE TITLE
Layout Caching Key Incorrect

### ISSUE THREAD

**Issue by siosphere** [tes/compoxure#112]
It breaks in your example, when it generated the layout caching key. In proxy.js it loads the layoutConfig:
`var layoutConfig = utils.getBackendConfig(config, layoutUrl);`

In the example this loads the default config, with cacheKey set to: `"backend:{{url:path}}"`

however, when it replaces the parameter, instead of replacing url:path with the url of the layout, it replaces it with the url of the first request, which gets a cache hit and returns whatever the backend returned for that cache key, not what the layout would return.
`
Core.render(layoutConfig.cacheKey, req.templateVars)
`
Should be updated to take into account the url of the layout

**Comment by noahwiener** [comment]
Thank you for raising this issue, and for clarifying a potential problem when using layout. After our team has done some investigation, we don't believe a code change is necessary.  I've added documentation to the readme on using `layout` here: https://github.com/tes/compoxure/commit/a2463e2f396aab894af49adb251192064e1b53cc

For an example taken from the config of our service using compoxure, here is how we handle the layout cachekey for our templating service:

```
    {
      "name": "service-layout-template",
      "pattern": "/layout-template/template/.*",
      "target": "{{server:layout-template}}",
      "cacheKey": "layout:{{layout}}:{{cookie:siteCountry}}:{{device:type}}"
    },

```

Please do follow up if this isn't working for you, or if there's anything else that can be clarified here or in the documentation

**Comment by siosphere** [comment]
Perfect! The {{layout}} is exactly what I was looking for.
