### ISSUE TITLE
Optional query param to flush the cache

### ISSUE THREAD

**Issue by sithmel** [tes/compoxure#114]
I think it would be extremely useful to have a a query param that flush the cache for a specific page (including fragments and layout)

**Comment by gabceb** [comment]
Why not make a param that changes at request time that would just bust the cache by changing the cache key? Allowing compoxure to flush the cache is a bit out of what is intended to do unless we make some kind of cli from it

**Comment by sithmel** [comment]
That will probably be enough and also easier to implement :smile:

**Comment by ksnll** [comment]
We implemented a query parameter (cx-no-cache) that will disable the cache for the request.
