### ISSUE TITLE
Composure as bottleneck

### ISSUE THREAD

**Issue by dglozic** [tes/compoxure#13]
Here is a concern that comes to mind - if every request goes through the composition service, isn't it now a chock point for the entire site? If I wire the micro-services directly to the routing proxy like nginx, and each micro-service is responsible for fetching and catching the fragments, the site is somewhat harder to write but with no single point od failure. What happens when composure service is down?

**Comment by cliftonc** [comment]
Closing due to age, but thanks for the discussion @dglozic and hope all is well these days!
