### ISSUE TITLE
backend 400 times out entire request

### ISSUE THREAD

**Issue by jbyers** [tes/compoxure#24]
When a fragment returns a 400 (and possibly other 4XX / 5XX that aren't 404), fail fast. Currently a 400 appears to time out the entire request.

**Comment by cliftonc** [comment]
Will take a look first thing tomorrow am.

**Comment by cliftonc** [comment]
Was due to a handler that responded to the 400 that didn't then terminate the response as it should, so an issue in our application vs Compoxure.
