### ISSUE TITLE
When a fragment 404 and an other one comes back after compoxure should not log an error

### ISSUE THREAD

**Issue by carolineBda** [tes/compoxure#28]
You get this error via this:

https://github.com/tes/compoxure/blob/1ac79e000d088239091b46ba5571738c2ddaf159/src/middleware/htmlparser.js#L164

Get request for Page X
- Parse, get 4 fragments (A, B, C, D)
- Make requests for fragment (A, B, C, D)
- Fragment A 404's so the response ends early with a 404 (https://github.com/tes/compoxure/blob/1ac79e000d088239091b46ba5571738c2ddaf159/src/middleware/htmlparser.js#L105)
- Responses from B, C, D come back, so the response "completes" - triggering this error.

In that case we should just ignore the other fragment for that request

**Comment by carolineBda** [comment]
So I believe that fixed it for fragment that 404 but it is still happening with other errors (we see it when other fragment returns 401).
I wonder if we should just not log this error at all?

**Comment by cliftonc** [comment]
Probably easiest, it isn't really an error the more you think about it.

**Comment by carolineBda** [comment]
Ok done:
https://github.com/tes/compoxure/commit/e8d28719c86c9f0b5f846a1e7a42e7b82499b615
