### ISSUE TITLE
latest parxer changes broke it

### ISSUE THREAD

**Issue by cliftonc** [tes/compoxure#37]
Need to investigate, but there were issues with latest parxer build where it wasn't closing off script tags, had to force it back to the older version and re-publish as it broke everything.

- Need to find out what issue is.
- Why wasnt it found in tests?

**Comment by gabceb** [comment]
Could not get to this today but will do so tomorrow unless someone beats me to it.

**Comment by cliftonc** [comment]
Figured it out, was my fault from the recent refactorings prior - just lucky that it hasn't popped up prior.  Will commit the changes to parxer and roll it out.
