### ISSUE TITLE
set cx-ignore-404=true by default

### ISSUE THREAD

**Issue by tomruttle** [tes/compoxure#43]
I can't think of many situations in which it's preferable to 404 a whole page rather than not show a fragment, and it's easy to forget to add this attribute to a compoxure element.

Thoughts?

**Comment by cliftonc** [comment]
Agree, this was originally setup in the early days with a static backend where all content was composed in, and actually we were using fragment 404s to 404 the whole page.

Not sure what we were thinking back then.  Easy to flip the default, but we should release as a semver bump as technically breaking.
