### ISSUE TITLE
Postprocessing links

### ISSUE THREAD

**Issue by RonRademaker** [tes/compoxure#58]
Hi,

I'm new to compoxure and think it looks like a promosing solution for a new microservice based project I'm starting. Currently I'm playing around with it to see if it fits my needs, so far I got most bases covered :tada: 

My question if it's possible to postprocess (relative) links from a microservice, let me explain using an example:

Microservice 1 provides an interface with basic CRUD operations on clients.
Microservice 2 provides an interface with basic CRUD operations on products.

Both use similar URLs internally, like /new to create a client / product, /update/\<id\> to update etc. Now I'd like compoxure to postprocess any links in the HTML response to prefix things coming from microservice 1 with /clients and things from microservice 2 with /products. So we get:

Microservice 1 ```<a href='/new'>Add a client</a>``` becomes  ```<a href='/clients/new'>Add a client</a>``` 
Microservice 2 ```<a href='/new'>Add a product</a>``` becomes  ```<a href='/product/new'>Add a client</a>``` 

This prefix I can than use to make sure the backend is able to fetch the correct template for the response (either by matching using the pattern and returning a fixed template or by creating a template service that determines which template is needed, not sure yet which approach would be best there).

**Comment by cliftonc** [comment]
You can make it do this, by adding plugins to the way it parses the html.

e.g. the plugin that parses the cx-test directive is here (this just echo's back what you put in, but with the templated variable subsitution).

https://github.com/tes/parxer/blob/master/lib/plugins/test.js

Plugins are at the moment hard coded in the configuration of the html parser:

https://github.com/tes/compoxure/blob/master/src/middleware/htmlparser.js#L166

You could easily add a config option that allowed you to pass in additional plugins when you instantiated the compoxure middleware.

Combine these two things together and you can make it do anything you like to the markup that passes through it.

In this model, I'd probably replace your ```href``` with ```cx-href``` and write the rule around that - this makes it opt in and leaves the other ```href``` tags un-molested.

Other examples of plugins for the parser are here:

https://github.com/tes/parxer/tree/master/lib/plugins

You're getting write down into the engine of how it works, but it's definitely possible.

**Comment by RonRademaker** [comment]
Thanks, starting to actually use compoxure in a real project made me realize it's 'better' to add the prefixing to the app.
