### ISSUE TITLE
To use compoxure with multiple micro-service instances on different containers or maybe paas

### ISSUE THREAD

**Issue by komushi** [tes/compoxure#61]
Appreciate Clifton's article at [https://medium.com/@clifcunn/nodeconf-eu-29dd3ed500ec](https://medium.com/@clifcunn/nodeconf-eu-29dd3ed500ec)

I still have some questions to apply on our system.

Assume I have a series of vertical-style - different business domains - micro-service instances which are managed and deployed by each team in containers on a same cloud foundry platform.

Let me use the sample in the article. Besides the 'Site masthead and navigation' part I have 4 microservice instances each uses different languages and frameworks and owns different ip adresses or domains.

Let's put the service discovery thing aside - assuming the domains are fixed.

http://resource.mydomain.com - spring boot app
http://review.mydomain.com - ruby on rail app
http://author.mydomain.com - angular.js backed by a non-ui node.js service
http://recommendation.mydomain.com - some php app

In this case how I am supposed to compose my backend.js and backend.html? Can compoxure make all these app work together?

Another question is that according to the example the backend instance works independently from the compoxure proxy. To realize HA and avoid bottle-neck which one should be added for more instances - scale-out?

Thanks a lot.

**Comment by cliftonc** [comment]
Sorry for the delay, I'll find some time tomorrow to post some sample configuration and HTML that does the above - its exactly how we operate here, and have had a mix of Node and Java apps composed together.

**Comment by komushi** [comment]
Look forward to that. Appreciate it a lot.

**Comment by HarshadUpadhyay** [comment]
Hi,

I am also trying to create composite UI with different UI sections serviced from different docker containers.  

Is it possible to get some sample configuration?

Thanks

**Comment by cliftonc** [comment]
There is a super simple example here:  https://github.com/cliftonc/compoxure-talk

**Comment by cliftonc** [comment]
The https://github.com/tes/compoxure-example repo now has a fully functional example that includes apps, services and a layout service.

**Comment by cliftonc** [comment]
No update, but the example is now linked in the readme.
