### ISSUE TITLE
Export and import html tags to improve web performances

### ISSUE THREAD

**Issue by jhaeyaert** [tes/compoxure#62]
Hi,

First of all, sorry for the approximative english (not my native language).

In a micro applications / services architecture, each application is responsible of a small piece of functionalities of a bigger system.

In order to be able to deploy each application independently, I want no coupling between each applications (I think this is the purpose of compoxure ;-).

My question is about dealing with resources required by an application but which need to be inserted at right place when rendering the whole page.

I'll try to explain myself with a simple example, not very pertinent in real world case but simple enough to understand.

So, we could imagine this case :

- homepage application : responsible to render the home page of a website
- header application : responsible to manage all header stuffs (internal app)
- footer application : responsible to render footer information (internal app)

**homepage** main template looks like this :
```
<html>
   <head>
      <link type="text/css" rel="stylesheet" href="http://cdn/common.css" />
   </head>
   <body>
      <div cx-url="http://page-header-app" />
      ...
      <div cx-url="http://page-footer-app" />
   </body>
</html>
```
Header and footer fragments are included into body section.

**header** looks like this :
```
<link type="text/css" rel="stylesheet" href="http://cdn/header.css" />
 <div>
      <p>This is my fantastic Header page</p>
</div>
```
I want the header application to be responsible to require the needed css, js and so on.

**footer** fragment could look like this :
```
<link type="text/css" rel="stylesheet" href="http://cdn/footer.css" />
 <div>
      <p>This is my fantastic Footer fragment</p>
</div>
```
In the same way, I want the footer application to be responsible to require the needed css, js and so on.

Currently, the page will be rendered like this :
```
<html>
   <head>
      <link type="text/css" rel="stylesheet" href="http://cdn/common.css" />
   </head>
   <body>
      <link type="text/css" rel="stylesheet" href="http://cdn/header.css" />
      <div>
         <p>This is my fantastic Header page</p>
      </div>
      ...
      <link type="text/css" rel="stylesheet" href="http://cdn/footer.css"  />
      <div>
         <p>This is my fantastic footer page</p>
      </div>
   </body>
</html>
```

As you can see, include of css into body part is not really good. Also, sometimes, some js have to be inserted into <head> section (sometimes not).

So, for better web performances, I would like the homepage result to be optimized for browser rendering like this :

```
<html>
   <head>
      <link type="text/css" rel="stylesheet" href="http://cdn/common.css" />
      <link type="text/css" rel="stylesheet" href="http://cdn/header.css" />
      <link type="text/css" rel="stylesheet" href="http://cdn/footer.css"  />
   </head>
   <body>
      <div>
         <p>This is my fantastic Header page</p>
      </div>
      ...
      <div>
         <p>This is my fantastic footer page</p>
      </div>
   </body>
</html>
```

Is there a way to achieve this using compoxure ? I imagined a solution using special tag attributes that could be parsed and replaced on the fly, ex :

Home :
```
<html>
   <head>
      <link type="text/css" rel="stylesheet" href="http://cdn/common.css" />
      <link cx-import="css" />
      <script cx-import="js" />
   </head>
   <body>
      <div data-loc="http://page-header-app" />
      ...
      <div data-loc="http://page-footer-app" />
   </body>
</html>
```

Header :
```
<link type="text/css" rel="stylesheet" href="http://cdn/header.css"  cx-export="css">

 <div>
      <p>This is my fantastic Header fragment</p>
</div>
```

Footer :
```
<link type="text/css" rel="stylesheet" href="http://cdn/footer.css"  cx-export="css">

 <div>
      <p>This is my fantastic Footer fragment</p>
</div>
```

Each tag marked with `cx-export="css"` (or `cx-export="xxxx"`) could replace the tag marked with `cx-import` (or `cx-import="xxxx"`). This way, I can manage external templates dependencies into each applications but "control" the insertion into the whole page using these kind of directives. In the same time, I do not need to modify my homepage template header even if i add other fragments that could use other css, js resources.

What do you think about this kind of feature ?

**Comment by cliftonc** [comment]
This is exactly what the cx-bundle directive does, but it is hugely opinionated and assumes you are putting the bundles of js and css in a certain structure on a CDN and your services return version headers that allow compoxure to use the correct version for the service.

You can see an example in the example folder of compoxure, and also in the tests for bundles.

We use this a lot at TES (have done for a year+), but it needs a better document to explain how it works, what the conventions are - as it is very specific and actually linked to our other tool (bosco) that creates the bundles for each service and pushes to the CDN.

I'll leave this open and write a clear blog post / addition to the readme that explains it so we can then figure out if it helps you or not!

**Comment by jhaeyaert** [comment]
Thanks for the quick response. 

I don't really understand how the cx-bundle works and if it allows to declare the bundle in child fragment template without declare it into the backend html template (ex : declare it in footer html without declare it in homepage html).

Is the cx-bundle declaration allows to include js and css into the head section of the final html structure ?
In the same time, is it possible to include some resources at the bottom or anywhere else (ex : some js have to be loaded as late as possible).

**Comment by cliftonc** [comment]
At the moment you do have to declare the bundle in the backend template, but given you add the cx-url fragment there anyway it's not too much of an overhead.

You can put the bundle wherever you need to in the page.

**Comment by jhaeyaert** [comment]
Ok got it. 

So, if I need to modify my footer application to add some javascript but I want the script to be include in the head section of the whole page (that is not managed by the footer app but by the homepage app), I need to modify and redeploy the homepage app too ?

**Comment by cliftonc** [comment]
Yes, at the moment that's how you have to do it.  We did once discuss
placeholder tags where you could have content from fragments placed in
other parts of the page (definitely possible), but it hasn't been built.

**Comment by cliftonc** [comment]
Closing as we haven't continued the discussion, please re-open if you want further help.
