### ISSUE TITLE
POST request to microservice

### ISSUE THREAD

**Issue by RonRademaker** [tes/compoxure#64]
Hi,

I'm currently building our first compoxure powered application. We use PHP for most microservices. If I post to compoxure, the requests are transformed to GET request. This is similar to what has been described in #57. The solution provided there, the ```passThrough``` options results in a POST to the backend. This is not what we are looking for, I want to request to the backend to remain a GET, but I want the request to the microservice to be a POST (with all the post data). How do I achieve this?

**Comment by cliftonc** [comment]
Not sure I quite get what you're trying to do?

At TES, when we want to post to a microservice we just post to it directly, not via PC.

```
GET tes.com/my-page
   -> backend:    GET page-service.internal.com
   -> fragment:   GET fragment-service.internal.com
```

If that page then has a form or action that I want to post something back to the ```fragment-service.internal.com```, then we just post straight to it.

```
POST tes.com/api/fragment-service
   -> Response is 301 tes.com/my-page
```

We have nginx in front of page composer, where we map the various routes to the right place.  So ```tes.com/api/fragment-service``` goes directly to the service and not compoxure.

Not sure if this helps?

**Comment by RonRademaker** [comment]
I get what you're saying and I've been trying to get it to work. I got the basics working, but how do you deal with failed server side checks. For example, we got a registration form in a microservice. One of the server side checks is checking if the given e-mail address is already known. If it is, the form is presented again (pre-filled of course) with a little message about what's wrong. In this case there is no redirect in the response, so the user is presented with just the output of the microservice.

**Comment by gabceb** [comment]
Over here we would submit the form via a POST to an api endpoint if the called returned json (which is what we mostly do) or a custom endpoint that is exposed on nginx with the microservice as the upstream which again, bypasses PC.

If your POST response has PC fragments on it (which I am assuming is what makes this problem interesting) you can probably hack it out by 301ing after the POST to the PC GET endpoint and map custom query params to the fragment params and then render with the appropriate errors? Again, we favor json APIs over forms over here which is why dont have a good solution for it.

@cliftonc can chime in if he has any more ideas

**Comment by cliftonc** [comment]
Yep, what I was going to add.  We submit the form with javascript to an API bypassing compoxure. 

We refer to it internally as Page Composer = PC in @gabceb comments above.

**Comment by RonRademaker** [comment]
The POST response doesn't have compoxure fragments, it is a compoxure fragment itself. Something like:

PC template:
```
<html>
... all kinds of things that make the page appealing to users
<div cx-url='{{server:profiles}}/profile/register'>
// the profiles service fills this with a registration form that send with POST. If everything is OK it's redirected to /profile/registered which will be passed to compoxure by the webserver, but if it's not it just outputs the form again with errors. As the POST request circumvents compoxure, the result doesn't have 'all kinds of things that make the page appealing to users'
</div>
... all kinds of things that make the page appealing to users
</html>
```

**Comment by RonRademaker** [comment]
I think for me the easiest solution for our setup would be to be able to configure servers (in the parameter section) in a way that all POST data would be passed through to that server (but never to the backend). But I don't know if or how that would work in compoxure, it should be something in the htmlparser. Which now uses the ```ReliableGet``` (which name suggests it won't be suitable for posts).

**Comment by cliftonc** [comment]
It might be technically possible to allow a POST via compoxure, and then run the response through the htmlparser, but I do think that the pattern of POST then re-direct is a better one to use in general.

ReliableGet could proxy POST's as well as GET's, but it would need a PR on that project as by their nature POSTs must never be cached, and ReliableGet is all about caching.

If you'd like to have a go at it and get it working we would definitely accept the PRs.

**Comment by RonRademaker** [comment]
We've updated our services to return JSON, which also results in a better user experience 😄

**Comment by cliftonc** [comment]
Great, glad you found a solution that worked for you.
