### ISSUE TITLE
Backend timeout looks like a request timeout

### ISSUE THREAD

**Issue by RonRademaker** [tes/compoxure#71]
The timeout defined in the backend section seems to be a timeout for the entire request. If I configure it lower than the time required to get the full response, but fast enough to get the template from the backend I get errors like: 

``` Timeout exceeded, failed to respond in 100ms. Failed Fragment: http://XXX/account/ ```

The fragment timeout however is set much higher in the template:

``` 
<div cx-url="{{server:status}}/account/" cx-timeout="4s">
</div>
```

**Comment by cliftonc** [comment]
Well spotted, it is the overall response timeout, makes much more sense if this is done as an aggregation of the fragment timeouts.

I notice in the PR that you are updating the timeout to whatever it is in the fragment.  Would it make more sense to only _increase_ the timeout if the current timeout is lower than the fragment?  e.g. have the backend timeout remain the default overall response time, but bump it up if you find a fragment that is willing to wait longer.

**Comment by RonRademaker** [comment]
Sounds good, I'll change the PRs

**Comment by RonRademaker** [comment]
I updated both PRs

**Comment by RonRademaker** [comment]
Looking at this some more, I wonder why the timeout in parxer state exists to begin with. This is the handling of a timeout that must occur after the initial backend template has been fetched (as it's part of parsing that template). These timeouts are already dealt with by the request in reliableget.

With the changes I get less timeouts, but if I force them (by adding sleep calls to my services), I sometimes get the error in the fragment part (which I expect), but also sometimes the error from parxer. 
I think the callbacks checking reliableget's request timeout and parxer state timeout both get called, sometime resulting in a timeout in the request (where it should IMO) and sometimes in parxer, which results in an empty page instead of just the missing fragment (either with or without an error depending on the quietFailure setting in the backend section). 

What is the purpose of the timeout in parxer, is it safe to just delete it or would it be better to allow enabling / disabling when fetching fragments (or something else).

**Comment by cliftonc** [comment]
From memory it was a safety net, a way to ensure it never got stuck or took too long (which under load would stack requests up and take the whole thing down).

It may be better to have the backend timeout be for the request to the backend, and perhaps add an optional parserTimeout that could be added if you wanted the larger timeout to be enabled?

**Comment by RonRademaker** [comment]
I opened a PR for this at https://github.com/tes/parxer/pull/12

**Comment by cliftonc** [comment]
Thanks, merged and published today.
