### ISSUE TITLE
Cannot run the example 

### ISSUE THREAD

**Issue by Tamagotcheat** [tes/compoxure#93]
Hello !

I saw an article about Compoxure and I wanted to try it but I think it doesn't work when I run it.
I'm able to clone the repository, do an "npm install" and "npm run start" and I can see the messages : 
"Example compoxure server on http://localhost:5000
 Example backend server on http://localhost:5001"

But when I go to http://localhost:5000 as mentioned in the instructions, I see nothing but "Service http://localhost:5001/ responded with status code 504"
So I try to go on http://localhost:5001 and here I'm able to see something : a page with some examples showing the difference between original source template and the result proxied via Compoxure.
BUT ! The problem is there is no difference between the contents so I suppose Compoxure is not running (or not working).
When I read the logs, I have errors about "cache missing for key backend:/".
Did I miss something important ? (For information, i use node v6.9.5)

I'm sorry if my problem is stupid but I think the example is supposed to work without any additional configurations. Or am I totally wrong ?

Thank you in advance !

**Comment by strife25** [comment]
I am also hitting this issue.

Here is my stack trace:

```
LOG debug: OK http://localhost:5001/
STAT timing for backend_localhost.responseTime | 42
~/Development/compoxure/node_modules/compoxure/src/middleware/htmlparser.js:275
        host: req.get('host')
                  ^

TypeError: req.get is not a function
    at getParxerOpts (~/Development/compoxure/node_modules/compoxure/src/middleware/htmlparser.js:275:19)
    at ServerResponse.parse (~/Development/compoxure/node_modules/compoxure/src/middleware/htmlparser.js:332:14)
    at ~/Development/compoxure/node_modules/compoxure/src/middleware/proxy.js:175:17
    at ~/Development/compoxure/node_modules/compoxure/src/middleware/proxy.js:106:20
    at ~/Development/compoxure/node_modules/reliable-get/index.js:123:13
    at args.(anonymous function) (~/Development/compoxure/node_modules/async-deco/src/log.js:22:9)
    at args.(anonymous function) (~/Development/compoxure/node_modules/async-deco/src/fallback-cache.js:54:11)
    at args.(anonymous function) (~/Development/compoxure/node_modules/async-deco/src/cache.js:35:13)
    at Immediate.<anonymous> (~/Development/compoxure/node_modules/async-deco/src/dedupe.js:23:15)
    at runCallback (timers.js:576:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by szxnyc** [comment]
Hello,

Same exact issue here.

**Comment by strife25** [comment]
I figured out why the example is failing in my comment above. Turns out the example is written to use the [connect](https://github.com/senchalabs/connect) server, which uses the nodejs-native request objects. However, the call to `req.get` fails with this assumption. This is because `.get` is a method available on request objects returned from [Express.js](https://expressjs.com/en/4x/api.html#req.get). 

As such, it looks like the example is broken since the project does not look to support `connect` from what I can tell. I was able to get things working by writing a basic example with express.

**Comment by gabceb** [comment]
Hi @strife25. I have not ran the example for a while but using Express instead of connect is correct. We run all pur microservices on Express 4. Can you submit a PR with tha fix for the example? If you hit another snag let me know and I'll try to help

**Comment by env0der** [comment]
@gabceb @strife25 I had the same issue today while doing an evaluation of `Compoxure`. Please look at #95 that fixes it. Special thanks to @strife25 for a hint about using `Express`.
