### ISSUE TITLE
Getting Started Instructions

### ISSUE THREAD

**Issue by linusthe3rd** [tes/compoxure#94]
Hello,

I am exploring different frameworks to help incorporate UI decomposition into my project so we can break up a monolithic UI codebase. Compoxure looks interesting to me, but I am not sure how to actually start getting it all set up for my own project. I understand the configuration file documentation, but what is needed to start using this tool for my own app?

Looking at the example code, it seems like I have to write my own version of `proxy.js`. Would that be correct?

I know I have a lot of questions here, but it would be good to have some "Getting Started" documentation to help direct new developers looking to adopt this project.

**Comment by cliftonc** [comment]
Correct - you need to create a simple express app that you add the middleware in this project to, and pass in the config to.  The version in example/proxy.js is about as simple as it gets.  Our version live here at TES isn't much more complex than that!

I've been meaning to write an up to date blog post to describe how we use it fully here, with better production ready code examples - I'll use our next hack day here at Tes to do that.

**Comment by rualatngua** [comment]
+1
@cliftonc I'm waiting for your blog post to describe how we use it fully. 

https://www.youtube.com/watch?v=l1GmfbblLcE great talk and awesome insight. Compoxure is very interesting and we hope it can help us to decompose our website and leverage our culture.

**Comment by cliftonc** [comment]
Thanks for the nudge, I'll see if I can carve out the time do pull this together.

**Comment by cliftonc** [comment]
I've created a simple project that mimics the service we have in production here at Tes: 
 https://github.com/tes/compoxure-example.

**Comment by cliftonc** [comment]
I've also now added a layout service, that demonstrates how we use a shared layout and slots to do an additional level of composition.

**Comment by cliftonc** [comment]
Closing as no response, but the link above is now in the readme so hopefully that helps!
