### ISSUE TITLE
Simplify Caching via @bettiolo

### ISSUE THREAD

**Issue by cliftonc** [tes/compoxure#96]
Right now we have a two way caching system. Downstream set cache headers as well as fragment and page composer configuration. I think that this duality adds unnecessary complications.

With the removal of the automagic cache, we have a saner config where we only cache fragments where explicitly set. I would extend this concept and make so that it is always the responsibility of the fragment itself to return appropriate cache headers, as the author of the fragment would know what is the validity of the fragment generated, and drop cache configuration in page composer's config and fragment attributes.

@bettiolo

**Comment by cliftonc** [comment]
It's a choice of scattering cache-control around or centralising it.

Originally it felt simpler to centralise it and make it declarative. NoCache=true is better (?) than copy pasting a string around services where people may not understand why.

I think removing the ability to declare something explicitly in page composer back end config or fragment config as no-cache is a big thing, we should discuss if it really will simplify things or actually make it harder to determine what the state of a page is.

I will also move this discussion to compoxure repo as it should live there.

**Comment by bettiolo** [comment]
Except if there are not other ideas, we should probably close this...

**Comment by petesiss** [comment]
Curious to know if you decided to put this in a roadmap, or if you in fact decided not to change it.

**Comment by cliftonc** [comment]
We decided to leave it as it is.
