### ISSUE TITLE
Compoxure Slots Usage

### ISSUE THREAD

**Issue by stefanklokgieters** [tes/compoxure#99]
Hi,

Yesterday I installed Compoxure to see what it could do for me looking at including multiple Micro Services into one of our existing pages. I am really amazed by all its functionality!

I am able to get Compoxure up and running and even to include a external application in one of the placeholders. Currently it returns the full HTML page (head, body etc) while I am more interested in grabbing just a specific set of elements from that response. Looking at the documentation I could use the `cx-define-slot` and `cx-use-slot` html attributes. My application is sending a `"cx-layout": "http://localhost:8080/"` header which then can be picked by Compoxure. Unfortunately this is not working for me after hours of trying and the documentation is relatively limited (not harm intend).

Perhaps I am doing something wrong or it's just not working as it should. Can someone help me out with this?

Thanks in advance!

Cheers,
Stefan

**Comment by cliftonc** [comment]
@stefanklokgieters huge apologies for not spotting this issue - my github feed is swamped.  Assume you've either moved on with your life or have solved it?  Happy to assist, and now that we have https://github.com/tes/compoxure-example I'll add a layout service to it to show how slots can be used.

**Comment by cliftonc** [comment]
https://github.com/tes/compoxure-example now has a fully working layout service, and an app that uses slots:

Layout: https://github.com/tes/compoxure-example/blob/master/layout/static/layout.html

App: https://github.com/tes/compoxure-example/blob/master/app/static/index.html

**Comment by cliftonc** [comment]
Closing as links above are a working example, and are now in the readme.
